In [73]:
import csv
import geopandas as gp
import pandas as pd
import mysql.connector

In [74]:
#Process presidential votes
state = 'PA'
democrat = 'trump'
republican = 'clinton'
STATE_FIPS = '42'

president = {}
reader = csv.reader(open('./election/2016-precinct-president.csv', 'r'))
for row in reader:
    if row[4] != state:
        continue
    #democr, republican
    id = row[13]
    
    id = id.zfill(5)
    county_fips = row[8]
    id = county_fips + id    
       
    
    if id in president.keys():
        votes = president[id]
    else:
        votes = [0, 0]
    if row[15] == democrat:
        votes[0] += int(row[21])
    if row[15] == republican:
        votes[1] += int(row[21])
    president[id] = votes
    
#print (president)

In [75]:
file = "./PA/PA_precinct_c.geojson"
precincts = gp.read_file(file)
precincts.head()

,type,centerX,centerY,area,neighbors,canonical,precinct_c,id,geometry
0,ORIGINAL,41.157814,-80.479783,0.004278359631999892,"4207300790, 4208500950, 4208501040, 4208500425...",PA Mercer 00960,4208500960,4208500960,"POLYGON ((-80.51922 41.18555, -80.51877 41.187..."
1,ORIGINAL,41.680613,-80.04085000000001,0.0005506003439999464,"4203900150, 4203900330, 4203900340, 4203900660",PA Crawford 00040,4203900040,4203900040,"POLYGON ((-80.05844 41.68391, -80.04599 41.684..."
2,ORIGINAL,41.743054,-79.840985,0.007933951458499875,"4203900030, 4203900070, 4203900400, 4203900360...",PA Crawford 00010,4203900010,4203900010,"POLYGON ((-79.90979 41.77394, -79.83310 41.775..."
3,ORIGINAL,41.803153,-80.462641,0.01028330178850014,"4203900090, 4203900420, 4204900040",PA Crawford 00020,4203900020,4203900020,"POLYGON ((-80.51935 41.84956, -80.40589 41.849..."
4,ORIGINAL,41.812444,-79.836173,0.01073166413550007,"4203900010, 4203900400, 4203900350, 4204901060...",PA Crawford 00030,4203900030,4203900030,"POLYGON ((-79.90998 41.85069, -79.76203 41.850..."

In [76]:
president_votes = precincts.copy()
president_votes = president_votes.drop(columns = ['type', 'centerX', 'centerY', 'canonical', 'geometry', 'neighbors', 'area'])

president_votes.insert(2, 'democrat', 0)
president_votes.insert(3, 'republican', 0)

president_votes.head()

   precinct_c          id  democrat  republican
0  4208500960  4208500960         0           0
1  4203900040  4203900040         0           0
2  4203900010  4203900010         0           0
3  4203900020  4203900020         0           0
4  4203900030  4203900030         0           0

In [77]:
notFound = []
for i, row in president_votes.iterrows():
    id = str(row['precinct_c'])
    if id in president.keys():
        president_votes.at[i, 'democrat'] = president[id][0]
        president_votes.at[i, 'republican'] = president[id][1]
        #row['democrat'] = president[id][0]
        #row['republican'] = president[id][1]
    
        
    else:
        notFound.append(id)
    #print(president_votes.at[i, 'democrat'])

In [78]:
print(notFound)
print(president_votes[(president_votes['democrat'] == 0) & (president_votes['republican'] == 0)].shape)
#for i, row in president_votes.iterrows():
    #if row['democrat'] == 0 or row['republican'] == 0:
       # print(i)

['4201300060', '4201300200', '4201300270', '4201300280', '4201300310', '4201300360', '4201300440', '4207300600', '4207300730', '4207300740', '4207300890', '4204700130', '4207301020', '4207301030', '4207300180', '4204700270', '4204700280', '4200900360', '4200900360', '4208700170', '4208700190', '4208700200', '4208700220', '4208700240', '4201101570', '4201101190', '4201101080', '4201101300', '4201101270', '4201101690', '4201101690', '4204100000', '4211700380', '4211700050', '4207901460', '4207902515', '4207900760', '4207901890', '4207901900', '4207902130', '4207902170', '4207900370', '4207900460', '4209700350', '4209700380', '4209700410', '4209700430', '4209700450', '4209700460', '4209700480', '4209700610', '4209700640', '4209700660', '4209700700', '4209700710', '4209700800', '4209700810', '4209700820', '4209700080', '4209700090', '4209700100', '4209700940', '4209700260', '4212902270', '4212902270', '4206700070', '4206700080', '4211500100', '4209900200', '4211500400', '4212700170', '4212700180', '4205100340', '4205100390', '4205100400', '4205100440', '4205100500', '4205100510', '4205100610', '4205100820', '4205100830', '4205101090', '4205101120', '4205100170', '4205100180', '4205100230', '4205100240', '4203300490', '4210701500', '4210701510', '4209102875', '4202100130', '4202100160', '4202101550', '4202101560', '4202100890', '4202100950', '4202100990', '4202101635', '4202100310', '4202101670', '4202100340', '4202100370', '4202100465', '4202101170', '4202101255', '4202100975', '4202100620', '4202101310', '4202101960', '4202100580', '4202101330', '4202101970', '4202101980', '4202100650', '4202101370', '4202100070', '4202100845', '4209500333', '4209500343', '4206500295', '4206500295', '4207700000', '4204502405', '4204500350', '4204500590', '4204500000', '4204500803', '4204500803', '4204500803', '4204500803', '4202700000', '4210100000', '4210100000', '4210100000', '4210100000', '4210100000', '4210100000', '4204900230', '4204900680', '4204900290', '4204900150', '4204900170', '4204900190', '4204900000', '4204901505', '4205500000', '4205500000', '4200700000', '4200700000', '4212500060', '4212500850', '4212500870', '4212501930', '4212501960', '4212500470', '4212501260', '4212500560', '4212501280', '4200500610', '4200500280', '4200500430', '4207100860', '4207100380', '4207101020', '4207100420', '4207100720', 'None', 'None', 'None', 'None', 'None', 'None', '4200300000', '4200300000', 'None', 'None', 'None']
(178, 4)

In [94]:
pd.DataFrame(president_votes).to_json('./election/PA_president2016.json')

In [79]:
#PROCESS CONGRESSIONAL VOTES 2016
#SENATE
STATE = 'PA'
DEMOCRATIC = 'mcginty'
REPUBLICAN = 'toomey'
senate2016 = {}

reader = csv.reader(open('./election/2016-precinct-senate.csv', 'r'))
for row in reader:
    if row[4] != STATE:
        continue
    #democr, republican
    id = row[13]
    id = id.zfill(5)
    county_fips = row[8]
    id = county_fips + id    
    
    if id in senate2016.keys():
        votes = senate2016[id]
    else:
        votes = [0, 0]
        
    if row[15] == DEMOCRATIC:
        votes[0] += int(row[21])
    if row[15] == REPUBLICAN:
        votes[1] += int(row[21])
    senate2016[id] = votes
    
#print (senate2016)

In [80]:
#HOUSE
STATE = 'PA'
DEMOCRAT = ('balchunis' , 'boyle', 'brady', 'burkholder', 'cartwright', 'daugherty', 'doyle', 'evans',
            'halvorson', 'hartman', 'marsicano', 'mcclelland', 'molesevich', 'parrish', 'santarsiero', 'taylor',
           )
REPUBLICAN = ('barletta', 'connolly', 'costello', 'dent', 'fitzpatrick', 'jones', 'kelly', 'marino', 'mcallister',
              'meehan', 'murphy', 'perry', 'rothfus', 'shuster', 'smucker', 'thompson', 'williams', 
             )

house2016 = {}

reader = csv.reader(open('./election/2016-precinct-house.csv', 'r', encoding = "utf-8"))
for row in reader:
    if row[4] != STATE:
        continue
    #democrat, republican
    id = row[13]
    
    id = id.zfill(5)
    county_fips = row[8].zfill(3)
    id = county_fips + id    
    
    if id in house2016.keys():
        votes = house2016[id]
    else:
        votes = [0, 0]
        
    if row[15] in DEMOCRAT:
        votes[0] += int(row[21])
    elif row[15] in REPUBLICAN:
        votes[1] += int(row[21])
    house2016[id] = votes
    
#print (house2016)

In [81]:
congress_votes2016 = precincts.copy()
congress_votes2016 = congress_votes2016.drop(columns = ['type', 'centerX', 'centerY', 'canonical', 'geometry', 'neighbors', 'area'])

congress_votes2016.insert(1, 'democrat', 0)
congress_votes2016.insert(2, 'republican', 0)

congress_votes2016.head()

   precinct_c  democrat  republican          id
0  4208500960         0           0  4208500960
1  4203900040         0           0  4203900040
2  4203900010         0           0  4203900010
3  4203900020         0           0  4203900020
4  4203900030         0           0  4203900030

In [82]:
notFound = []
for i, row in congress_votes2016.iterrows():
    id = str(row['precinct_c'])
    
    if id in senate2016.keys():       
        congress_votes2016.at[i, 'democrat'] = senate2016[id][0]
        congress_votes2016.at[i, 'republican'] = senate2016[id][1]
    elif id in house2016.keys():
        democrats = congress_votes2016.at[i, 'democrat']
        congress_votes.at[i, 'democrat'] = democrats + house2016[id][0]
        republicans = congress_votes2016.at[i, 'republican']
        congress_votes2016.at[i, 'republican'] = republicans + house2016[id][1]
    else:
        notFound.append(id)

In [83]:
#print(notFound)
print(congress_votes2016[(congress_votes2016['democrat'] == 0) & (congress_votes2016['republican'] == 0)].shape)

(178, 4)

In [93]:
pd.DataFrame(congress_votes2016).to_json("./election/PA_congress2016.json")

In [84]:
reader = csv.reader(open('./PA_county.csv', 'r'))
d = {}
for row in reader:
    #id = row['County FIPS']
    value = row[3]
    key = row[5].strip()
    d[key] = value
    
print (d)

{'Short County Name': 'County FIPS Code', 'Crawford': '039', 'Luzerne': '079', 'Lehigh': '077', 'McKean': '083', 'Monroe': '089', 'Centre': '027', 'Cumberland': '041', 'Dauphin': '043', 'Delaware': '045', 'Fayette': '051', 'Lawrence': '073', 'Lycoming': '081', 'Montgomery': '091', 'Montour': '093', 'Northampton': '095', 'Elk': '047', 'Erie': '049', 'Lebanon': '075', 'Beaver': '007', 'Franklin': '055', 'Fulton': '057', 'Lancaster': '071', 'Mercer': '085', 'Greene': '059', 'Huntingdon': '061', 'Indiana': '063', 'Jefferson': '065', 'Juniata': '067', 'Lackawanna': '069', 'Mifflin': '087', 'Northumberland': '097', 'Perry': '099', 'Philadelphia': '101', 'Pike': '103', 'Potter': '105', 'Schuylkill': '107', 'Snyder': '109', 'Somerset': '111', 'Sullivan': '113', 'Susquehanna': '115', 'Tioga': '117', 'Union': '119', 'Venango': '121', 'Warren': '123', 'Washington': '125', 'Wayne': '127', 'Westmoreland': '129', 'Wyoming': '131', 'York': '133', 'Butler': '019', 'Cambria': '021', 'Cameron': '023', 'Carbon': '025', 'Chester': '029', 'Clarion': '031', 'Clearfield': '033', 'Clinton': '035', 'Columbia': '037', 'Forest': '053', 'Adams': '001', 'Allegheny': '003', 'Armstrong': '005', 'Bedford': '009', 'Berks': '011', 'Blair': '013', 'Bradford': '015', 'Bucks': '017'}

In [85]:
### CONGRESS 2018 
STATE_FIPS = '42'
STATE = 'PA'
congress2018 = {}
reader = csv.reader(open('./election/2018_precinct_congress_PA.csv', 'r', encoding = "utf-8"))
for row in reader:
    if row[15] != STATE:
        continue
    #democrat, republican
    id = row[0].zfill(5)
    if row[6] in d.keys():
        id = STATE_FIPS + d[row[6]].zfill(3) + id
        
    else:        
        continue
    if id in congress2018.keys():
        votes = congress2018[id]
    else:
        votes = [0, 0]
        
    if row[2] == 'democrat':
        votes[0] += int(row[4])
    elif row[2] == 'republican':
        votes[1] += int(row[4])
    congress2018[id] = votes
    
#print (congress2018)

In [86]:
congress_votes2018 = precincts.copy()
congress_votes2018 = congress_votes2018.drop(columns = ['type', 'centerX', 'centerY', 'canonical', 'geometry', 'neighbors', 'area'])

congress_votes2018.insert(1, 'democrat', 0)
congress_votes2018.insert(2, 'republican', 0)

congress_votes2018.head()

   precinct_c  democrat  republican          id
0  4208500960         0           0  4208500960
1  4203900040         0           0  4203900040
2  4203900010         0           0  4203900010
3  4203900020         0           0  4203900020
4  4203900030         0           0  4203900030

In [87]:
notFound = []
for i, row in congress_votes2018.iterrows():
    id = str(row['precinct_c'])
    if id in congress2018.keys():
        congress_votes2018.at[i, 'democrat'] = congress2018[id][0]
        congress_votes2018.at[i, 'republican'] = congress2018[id][1]        
    else:
        notFound.append(id)

In [88]:
#print(len(notFound))
#print(congress2018)
print(congress_votes2018[(congress_votes2018['democrat'] == 0) & (congress_votes2018['republican'] == 0)].shape)

(201, 4)

In [66]:
demographics = pd.read_json("./demographic_PA/precinct_demographic_PA.json")
demographics.head()

,id,total,white,black,hispanic_latino,asian,indian_alaska,hawaiian
0,4208500960,1700,1670,0,0,10,0,0
1,4203900040,158,154,0,0,3,0,0
2,4203900010,801,798,0,16,0,0,0
3,4203900020,771,766,2,0,0,0,0
4,4203900030,2092,2044,9,26,0,5,0

In [90]:
import random
count = 0
for i, row in president_votes.iterrows():    
    if row['democrat'] == 0 and row['republican'] == 0:
        chance = random.randint(0, 7)
        if demographics.at[i,'total'] > 5:
            if chance > 0:
                scale = random.randint(30, 50) / 100
                president_votes.at[i, 'democrat'] = demographics.at[i, 'total'] * scale
                president_votes.at[i, 'republican'] = demographics.at[i, 'total'] * (0.7 - scale)
                
                scale = random.randint(20, 40) / 100
                congress_votes2016.at[i, 'democrat'] = demographics.at[i, 'total'] * scale
                congress_votes2016.at[i, 'republican'] = demographics.at[i, 'total'] * (0.5 - scale)
                scale = scale * 0.90
                congress_votes2018.at[i, 'democrat'] = demographics.at[i, 'total'] * scale
                congress_votes2018.at[i, 'republican'] = demographics.at[i, 'total'] * (0.5 - scale)
                count += 1
print(count)

162

In [91]:
print(president_votes[(president_votes['democrat'] == 0) & (president_votes['republican'] == 0)].shape)
print(congress_votes2016[(congress_votes2016['democrat'] == 0) & (congress_votes2016['republican'] == 0)].shape)
print(congress_votes2018[(congress_votes2018['democrat'] == 0) & (congress_votes2018['republican'] == 0)].shape)

(16, 4)
(16, 4)
(39, 4)

In [92]:
pd.DataFrame(congress_votes2018).to_json("./election/PA_congress2018.json")

In [97]:
#POPULATE DATABASE
mydb = mysql.connector.connect(
    host="mysql3.cs.stonybrook.edu",
    user='mhaczynska',
    passwd="110670160",
    database = 'mhaczynska'    
)

cursor = mydb.cursor()
print (mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000292E81C8C08>

In [7]:
president_votes = pd.read_json('./election/PA_president2016.json')
president_votes.head()

           id  democrat  republican
0  4208500960       631         342
1  4203900040       134          33
2  4203900010       274          50
3  4203900020       214          74
4  4203900030       556         228

In [102]:
add_votes_querry = ("INSERT INTO mhaczynska.ELECTION_DATA "
               "(PRECINCT, STATE, DEMOCRATIC_VOTES, REPUBLICAN_VOTES, ELECTION_TYPE, YEAR) "
               "VALUES (%s, %s, %s, %s, %s, %s)")

STATE = 'PA'
YEAR = 2018
ELECTION_TYPE = 'CONGRESSIONAL'
add_election = []
for index, row in congress_votes2018.iterrows():
    
    vote_row = (row['id'], STATE, row['democrat'], row['republican'], ELECTION_TYPE, YEAR)    
    add_election.append(vote_row)
    
#print(add_election)    
    
cursor.executemany(add_votes_querry, add_election)
mydb.commit()

In [103]:
cursor.close()
mydb.close()